apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: docker-imagepullsecret
spec:
  externalSecretName: docker-imagepullsecret
  namespaceSelector:
    matchLabels: {}
  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: aws-ssm-parameter-store
      kind: ClusterSecretStore
    refreshInterval: 5m
    target:
      name: docker-imagepullsecret
      creationPolicy: Owner
      deletionPolicy: Retain
      template:
        type: kubernetes.io/dockerconfigjson
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: /setup/hypersign/eks/dockerconfig
--- 
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    name: aws-ssm-parameter-store
    kind: ClusterSecretStore
  refreshInterval: 5m
  target:
    name: slack-credentials
    creationPolicy: Owner
  data:
    - secretKey: slack-credentials
      remoteRef:
        key: /setup/hypersign/eks/slack

