apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
    {{- include "validator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 9300
      targetPort: 9300
  type: {{ .Values.service.type }}
