prometheus:
  prometheusSpec:
    nodeSelector:
      Role: infra
    additionalScrapeConfigs:

    - job_name: cosmos
      metrics_path: /metrics
      static_configs:
        - targets:
          - hypersign.validator.svc.cluster.local:26660
          #- hypersign-node.node.svc.cluster.local:26660

    - job_name: validator
      scrape_interval: 15s
      metrics_path: /metrics/validator
      static_configs:
        - targets:
          - cosmos-exporter-validator.validator.svc.cluster.local:9300
          #- hypersign-cosmos-exporter-node.node.svc.cluster.local:9300
          # list of validators you want to monitor
          labels:
            address: hidvaloper1e8gele4kgu45ser7xgkrjrjfacfukczyc72ttk
#      relabel_configs:
#        - source_labels: [__address__]
#          target_label: __param_address
#        - source_labels: [__param_address] # maybe not required
#          target_label: instance # maybe not required
#        - target_label: __address__ # maybe not required
#          replacement: hypersign-cosmos-exporter-validator.validator.svc.cluster.local:9300
#          #replacement: <node hostname or IP>:9300

    - job_name: wallet
      scrape_interval: 15s
      metrics_path: /metrics/wallet
      static_configs:
        - targets:
          - cosmos-exporter-validator.validator.svc.cluster.local:9300
          #- hypersign-cosmos-exporter-node.node.svc.cluster.local:9300
          labels:
            address: hid1e8gele4kgu45ser7xgkrjrjfacfukczy8uaprf
#      relabel_configs:
#        - source_labels: [__address__]
#          target_label: __param_address
#        - source_labels: [__param_address] # maybe not required
#          target_label: instance # maybe not required
#        - target_label: __address__ # maybe not required
#          replacement: hypersign-cosmos-exporter-validator.validator.svc.cluster.local:9300

    - job_name: 'validators'
      scrape_interval: 15s
      metrics_path: /metrics/validators
      static_configs:
        - targets:
          - cosmos-exporter-validator.validator.svc.cluster.local:9300
          #- hypersign-cosmos-exporter-node.node.svc.cluster.local:9300

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      Role: infra
    alertmanagerConfiguration:
      name: global-alertmanager-configuration
    secrets:
      - slack-credentials