apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
    {{- include "validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1317
      name: api
    - port: 9090
      name: grpc
    - port: 26656
      name: p2p
    - port: 26657
      name: rpc
      name: rpc
    - port: 9091
      name: port
    - port: 26660
      name: prometheus
    - port: 9100
      name: validator-exporter
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}