#provider: "aws"

replicaCount: 1

strategyType: RollingUpdate

imagePullSecrets:
  - name: docker-imagepullsecret

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

node:
  env:
    bondDenom: uhid
    benchPrefix: hid1

image:
  repository: xxxx/cosmos-exporter
  pullPolicy: IfNotPresent
  tag: dev

fullNodeAppName: hypersign

service:
  type: ClusterIP

nodeSelector:
  Role: full-node

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "full-node"
  effect: "NoSchedule"

affinity: {}