#provider: "aws"

replicaCount: 1

strategyType: RollingUpdate

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

node:
  env:
    bondDenom: uhid
    benchPrefix: hid1

image:
  repository: hora1427/cosmos-exporter
  pullPolicy: IfNotPresent
  tag: test

service:
  type: ClusterIP

nodeSelector:
  Role: full-node

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "full-node"
  effect: "NoSchedule"

affinity: {}